### ISSUE TITLE
PushServiceSocket: AuthorizationFailedException: Authorization failed!

### ISSUE THREAD

**Issue by Trolldemorted** [Turasa/libsignal-service-java#9]
I upgraded to your current master and re-linked my slave, now all users are considered non-signal users because the PushServiceSocket does not like my slave, and thus i cannot send anything:

```
02-19 12:40:34.704 10821-13004/org.thoughtcrime.securesms W/ConversationActivity: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
  at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:548)
  at org.whispersystems.signalservice.internal.push.PushServiceSocket.getContactTokenDetails(PushServiceSocket.java:416)
  at org.whispersystems.signalservice.api.SignalServiceAccountManager.getContact(SignalServiceAccountManager.java:309)
  at org.thoughtcrime.securesms.util.DirectoryHelper.refreshDirectoryFor(DirectoryHelper.java:125)
  at org.thoughtcrime.securesms.ConversationActivity$13.doInBackground(ConversationActivity.java:923)
  at org.thoughtcrime.securesms.ConversationActivity$13.doInBackground(ConversationActivity.java:912)
  at android.os.AsyncTask$2.call(AsyncTask.java:295)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)
```

**Comment by Trolldemorted** [comment]
i think this is a issue on my side. will reopen after closer investigation if neccessary.
